### ISSUE TITLE
SqueakeCraft speaks the wrong remote media protocol

### ISSUE THREAD

**Issue by sofar** [Pipsqueake/SqueakeCraft#1]
Most servers are running 0.4.15 or 0.4.16 and offer remote media loading, however the SqueakeCraft client only speaks the remote media protocol that was in version 0.4.13. This results in the client spamming the remote media server with hundreds of GET requests resulting in a 404.

Either disable remote media loading in the squeakecraft client (disable curl), or upgrade the client to support 0.4.15+ remote media client protocol, please. 

As it is right now, this is wasting player's time when they log in to servers that enabled remote media server and do the correct protocol.

**Comment by Pipsqueake** [comment]
This project has been closed and should no longer be available for download.
The code as it is will not be updated and this issue will be closed.
Thank you for reporting this issue in case the project is reopened in the future!

**Comment by sofar** [comment]
Geesh, not even an acknowledgement of the problem?

**Comment by Pipsqueake** [comment]
I did not deny that the issue exists. I did thank you for informing me of the issue and let you know the app should not be available currently.

If this project gets reopened then this and a few other outdated items will be fixed :)

Thank you again for reporting the issue :)

**Comment by sofar** [comment]
Does my bug report sound like I was looking for the service desk answer?

The reason I report this is because I see SqueakeCraft clients connect to *my* remote media server. And they cause thousands of 401's. Even after you wiped it off the appstore.

I'm not looking for your service desk. The one thing I have issues with is when I provide relevant and useful technical information to a github project that can be trivially escalated to a technical person and I get a canonical helpdesk reply that has been used on hundreds of customers. Hence my insistence on a meaningful technical reply instead.

So please, the next time, just say "maybe next revision, sorry, currently we're not spending time on this project" would suffice as an answer. It's obvious that I'm attempting to contact a developer, that I am a developer, and that I'm interested in a technical discussion and most likely won't ever pay for any of your products. In fact, I'm paying to support your customers by providing a remote media service to all minetest players which includes SqueakeCraft players. So, we're essentially a team. And I'm trying to help you.

Cheers.
